"""Initial migration.

Revision ID: 59216f3171bc
Revises: 
Create Date: 2024-02-13 15:57:28.824430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59216f3171bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gym_slots')
    # ### end Alembic commands ###
